name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck
      
      - name: Lint shell scripts
        run: shellcheck bin/* scripts/*.sh

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      
      - name: Install BATS
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
      
      - name: Install bpkg
        run: |
          curl -Lo- http://get.bpkg.sh | bash
          echo "PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV
          which bpkg
      
      - name: Install dependencies
        run: |
          # Install Git
          sudo apt-get update
          sudo apt-get install -y git
          
          # Install GitHub CLI properly
          type -p curl >/dev/null || sudo apt-get install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      
      - name: Install cli from local package
        run: |
          cd $GITHUB_WORKSPACE
          bpkg install . -g
          echo "Installation completed with exit code: $?"
          find /usr/local/bin -name bdo || echo "bdo not found in /usr/local/bin"
          sudo find / -name bdo 2>/dev/null || echo "Could not find bdo anywhere"
          echo "PATH=$PATH"
          sudo ln -sf $(sudo find / -name bdo 2>/dev/null | head -1) /usr/local/bin/bdo || echo "Failed to create symlink"
      
      - name: Test CLI basic functionality
        run: |
          export PATH=$PATH:/usr/local/bin
          which bdo || echo "bdo not in PATH"
          sudo -E bdo help || echo "Failed to run with sudo"
          
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Update package.json version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          jq ".version = \"$VERSION\"" package.json > package.json.tmp
          mv package.json.tmp package.json